steps:
  test:
    image: golang:1.25-alpine
    commands:
      - go mod download
      - go test -v ./...
    when:
      - event: push
        branch: main
        message:
          exclude: "*[test]*"

  publish-image:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: ghcr.io
      repo: ghcr.io/kraito585/rfad-tui-backend
      tags: latest
      username: Kraito585
      password:
        from_secret: github_token
    when:
      - event: push
        branch: main
        message:
          exclude: "*[build]*"

  deploy:
    image: docker:cli
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u Kraito585 --password-stdin
      
      - docker compose -f docker-compose.yml -p rfad pull api
      - docker compose -f docker-compose.yml -p rfad up -d api
      - docker image prune -f
    when:
      - event: push
        branch: main
        message:
          exclude: "*[deploy]*"

when:
  event: push
  branch: main