steps:
  test:
    image: golang:1.25-alpine
    commands:
      - go mod download
      - go test -v ./...
    when:
      - event: push
        branch: main
        message: "^((?!\\[test\\]).)*$" # Выполнять, только если в коммите НЕТ [test]

  publish-image:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: ghcr.io
      repo: ghcr.io/kraito585/rfad-tui-backend
      tags: latest
      username: Kraito585
      password:
        from_secret: github_token
    when:
      - event: push
        branch: main
        message: "^((?!\\[build\\]).)*$" # Выполнять, только если в коммите НЕТ [build]

  deploy:
    image: docker:cli
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Теперь эта папка реально пробросится, так как агент знает о ней
      - /home/docker:/data
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u Kraito585 --password-stdin
      # Читаем файл из смонтированной папки /data/ внутри контейнера
      - docker compose -f /data/docker-compose.yml pull api
      - docker compose -f /data/docker-compose.yml up -d api
      - docker image prune -f
    when:
      - event: push
        branch: main
        message: "^((?!\\[deploy\\]).)*$" # Выполнять, только если в коммите НЕТ [deploy]

when:
  event: push
  branch: main